### PR TITLE
Add WSL + running HTML5 in production

### PR DESCRIPTION
**Pull request by matiasilva**
Adds section on Windows Subsystem for Linux and addresses a common issue of how to run a customized version of HTML5 in prod. Inspired by [this thread](https://groups.google.com/forum/#!topic/bigbluebutton-dev/IZiDLqnYjEg).

### CODE REVIEW

**Comment by basisbit** [comment]
any source for reports of bbb actually working on Ubuntu 16.04 on WSL?

**Comment by matiasilva** [comment]
I can't confirm a full working setup but I use WSL to build these docs (runs perfectly with the docker command and can access on localhost:4000 out of the box) as well as to test changes (such as the PR I made for mirroring). I perhaps misunderstood the intention of having a VM. My idea was that those who are developing already have a working BBB dev server elsewhere and can play around with that. All of my changes have been using WSL over SSH to another machine.

**Comment by kaneki666** [comment]
--server-only options gives me error so i tried with it works..but it also creates also mobile build..is it prob if i use this build??

**Comment by matiasilva** [comment]
Interesting, I followed [this thread.](https://groups.google.com/forum/#!msg/bigbluebutton-dev/IZiDLqnYjEg/TkMsmGv1BgAJ)

**Pull request merged**
