### PR TITLE
Add brand new section on Scalelite

### PR DESCRIPTION
**Pull request by matiasilva**
With the rising demand for distributed, scalable BigBlueButton installations, we need appropriate documentation so that small-medium installations can set this up and themselves and bigger installations can seek commercial help. This PR adds 4 new sections: overview, deploy, configure and administration. It draws upon the existing documentation and jfederico's Medium article to provide a simple and easy way to install Scalelite. It is much easier if all information is available in one place.

If this PR is merged, the Scalelite documentation should be updated appropriately to point to the docs.

### CODE REVIEW

**Comment by basisbit** [comment]
please link the "jfederico's medium article" and related copyright information. What content did you copy from there?

**Comment by matiasilva** [comment]
Article [here](https://medium.com/@jesusfederico_39370/scalelite-lazy-deployment-745a7be849f6). I took one image as well as descriptions for each component of Scalelite. The image I assume is licensed in the public domain as it's just a diagram but it would be good for @jfederico to confirm this.

**Comment by ffdixon** [comment]
Copyright aside, we'll keep the Scalelite documentation separate for now.  The Scalelite project itself is not part of the BigBlueButton core repositories. 

I know the Scalelite maintainers have been releasing updates to the project based on community feedback and they would welcome suggested improvements (pull requests) to their documentation.

**Comment by matiasilva** [comment]
Fair enough. I'll close this then.

**Pull request closed without merging**
